M48
; DRILL file {KiCad 8.0.1} date 2024-04-02T12:31:18-0700
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-04-02T12:31:18-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.1
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0315
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0354
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C0.0394
%
G90
G05
T1
X5.05Y-5.15
X5.05Y-5.45
T2
X4.79Y-5.2602
X4.79Y-5.3602
T3
X5.52Y-5.1841
X5.52Y-5.44
X5.6972Y-5.1841
X5.6972Y-5.44
M30
